name: rick_and_morty
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  bloc: ^9.1.0
  build_runner: ^2.10.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  hive_ce: ^2.15.1
  http: ^1.6.0
  http_cache_client: ^1.0.4
  http_cache_core: ^1.1.3
  http_cache_hive_store: ^5.0.1
  injectable: ^2.7.1+2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.3
  injectable_generator: ^2.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/
