name: rick_and_morty
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  bloc: ^9.1.0
  build_runner: ^2.10.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  http: ^1.6.0
  injectable: ^2.7.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.3
  injectable_generator: ^2.11.1

flutter:
  uses-material-design: true
